### ISSUE TITLE
impossible to create from app

### ISSUE THREAD

**Issue by yalgva** [ericferon/glpi-dataflows#1]
Hello,

thank you for your great plugin !!!

1st bug, it is impossible to create from app, no save button appears

Thank you so much for your help

GLPI 9.2

**Comment by yalgva** [comment]
Hello,

The application is in apps structure, but when I save my dataflow, it dissapears and I don't have any data anymore

**Comment by yalgva** [comment]
If i save type in app structure it is not saved

**Comment by ericferon** [comment]
Do you have error messages, on screen or in the (sql or php) logs ?
Can you open new issues if your problem is not related to a preceding one ? The follow-up will be beter.
Best regards,
