### ISSUE TITLE
use of views as tables

### ISSUE THREAD

**Issue by Stoatwblr** [ericferon/glpi-dataflows#10]
FYI: it appears that glpi "clean" doesn't know about "delete view" vs "delete table" - you may wish to tweak the disable/uninstall scripts to explicitly remove them.

**Comment by Stoatwblr** [comment]
The problem with leaving the views behind is that they break mysqldump.

**Comment by ericferon** [comment]
Tweaking the delete was done, but there was a bug there.
It will be solved in the next version (v2.0.12).
Thank you,
