### ISSUE TITLE
Application à la source

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-dataflows#11]
Hello

What is 
![image](https://user-images.githubusercontent.com/42341169/54347082-88e6e880-4646-11e9-96c8-52506d4fa252.png)

when clicking on i or + we see nothing and  we can't add any application. It links on '...plugins/dataflows/front/fromswcomponent.php' but nothing on screen ?

**Comment by ericferon** [comment]
If you click on the dropdown list, you should see the list of Apps with their field "level" equal to 1 and located in the current entity.
Best regards,
