### ISSUE TITLE
Class 'PluginDataflowsDataflow' not found

### ISSUE THREAD

**Issue by peteredhair** [ericferon/glpi-dataflows#12]
On GLPI 9.4 when i install the plugin there is an error in the apache errolog file and the list of plugins disappears.

The error found in apache error log is the following:
PHP Fatal error:  Uncaught Error: Class 'PluginDataflowsDataflow' not found in /var/www/html/glpi/plugins/dataflows/hook.php:528\nStack trace:\n#0 /var/www/html/glpi/inc/plugin.class.php(1115): plugin_dataflows_MassiveActions('Plugin')\n#1 /var/www/html/glpi/inc/massiveaction.class.php(577): Plugin::doOneHook('dataflows', 'plugin_dataflow...', 'Plugin')\n#2 /var/www/html/glpi/inc/search.class.php(1587): MassiveAction::getAllMassiveActions(Object(Plugin), 0)\n#3 /var/www/html/glpi/inc/search.class.php(99): Search::displayData(Array)\n#4 /var/www/html/glpi/inc/search.class.php(80): Search::showList('Plugin', Array)\n#5 /var/www/html/glpi/front/plugin.php(44): Search::show('Plugin')\n#6 {main}\n  thrown in /var/www/html/glpi/plugins/dataflows/hook.php on line 528, referer: http://glpi.besseguros.pt/front/plugin.form.php

Congrats on the this great plugin.

**Comment by ericferon** [comment]
This problem does not appear in new version 9.5.
K.r,
