### ISSUE TITLE
Wrong link to application ?

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-dataflows#13]
Hello

plugin 2.1.0

when clicking on 'application source' or 'dest'
![image](https://user-images.githubusercontent.com/42341169/73277699-d6326100-41ea-11ea-8f2b-0c8c04943e14.png)

it links to a wrong link (intitulés) : I think the path is not good

it goes to 
plugins/**dataflows**/front/fromswcomponent.php

Best regards

**Comment by EC2311** [comment]
hello

In fact it's the same topic i opened last year ;) 

and you said that it list apps with level 1 

How is the application set to 1 ? Is it linked to 'father' ?

-> I have many applications to 0 : ok
-> I created a new one (Father for instance)
-> I made the link with the child to this application 'Father' : the level is set to '2' : why not to '1' ?

Thanks
Best regards

**Comment by ericferon** [comment]
These fields ("From Application" and "To Application") are pointing to a list of applications defined in the plugin "archisw". Technically, this list is built through a "view" in the GLPI database.
These views (1 for "From Application", 1 for "To Application") are selecting the applications with a "where" clause based on the "level" field. If you want to select other levels too, you can change these views in your installation (see sql/empty1.2.3.sql, lines 225 and following).
Now, in plugin "archisw", a simple application is created with level set automatically to "1" (the "level" field is read-only).
If you create a child (via the tab "App structures" and the button "Add") or if you link an application as child of another one via the field "As child of" in tab "Apps Structure"), the child should automatically receive the father's level plus 1.
There should be no application with level "0".
Best regards,

**Comment by EC2311** [comment]
Hello

Instead of putting the value in the script, and depending of 'end-users' need, what do you think to put this value (1 is default) in a parameter field ?

Best regards

**Comment by ericferon** [comment]
It's a good suggestion.
I have to examine whether it's feasible by using a standard parameter table (without creating a specific table for this plugin, with only 1 parameter), in a future version.
Best regards,
