### ISSUE TITLE
Bug : pas de bouton 'ajouter' destination connecteur

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-dataflows#14]
Bonjour

plugin 2.1.0

![image](https://user-images.githubusercontent.com/42341169/73345184-e4808b80-4283-11ea-9222-ccd17a3c32f4.png)

connecteur à la source : pas de bouton d'ajout

**Comment by ericferon** [comment]
Je n'ai pas ce problème, et je ne parviens pas à le reproduire : 
![image](https://user-images.githubusercontent.com/8736398/73534504-95705d00-4421-11ea-9145-00a546558fe4.png).
Bien cordialement,

**Comment by EC2311** [comment]
Bonjour

En mode debug, j'ai une erreur lors de l'affichage de la liste des connecteurs de destination
![image](https://user-images.githubusercontent.com/42341169/73635357-a6a8ac00-4663-11ea-9e39-745ef7e03f72.png)

puis si j'essaie d'en creer un : 
![image](https://user-images.githubusercontent.com/42341169/73635476-ef606500-4663-11ea-8291-75c11869d1eb.png)

**Comment by ericferon** [comment]
Pour une raison inconnue, la vue nécessaire n'existe pas dans votre base de données.
Il vous faut la créer manuellement avec la commande suivante, extraite de sql/empty-1.2.3.sql (lignes 222-223) : 
```
CREATE OR REPLACE VIEW glpi_plugin_dataflows_destinationconnectors as
SELECT `id`,`name`, `comment` FROM glpi_plugin_dataflows_sourceconnectors;
```
Bien cordialement,

**Comment by EC2311** [comment]
j'ai essayé la requete, mais visiblement toujours meme souci

voici la liste des tables existantes du plugin
![image](https://user-images.githubusercontent.com/42341169/73851210-6432cb00-482d-11ea-8b2c-f76ecf81bac2.png)

on devrait voir dataflow_sourceconenctors ou destinationconnectors ?
dans la requete on a : 
CREATE OR REPLACE VIEW glpi_plugin_dataflows_destinationconnectors as
SELECT `id`,`name`, `comment` FROM glpi_plugin_dataflows_**source**connectors;

**Comment by EC2311** [comment]
En fait je pense que la commande CREATE VIEW n'est pas autorisée... (dans mon contexte)

**Comment by EC2311** [comment]
Avec les droits la commande est ok :)

Resolu. 


Par contre je pense qu'il faut corriger els 2 requetes (230-237)
![image](https://user-images.githubusercontent.com/42341169/73943161-922d1380-48f0-11ea-9938-667822f9c427.png)
en spécifiant 'name' au lieu de id -> sinon on a les id des appli en dropdown et non leur nom...

**Comment by ericferon** [comment]
Non, il ne faut pas remplacer "id" par "name".
Entre parenthèses apparait normalement l'id (si vous l'avez spécifié dans vos préférences), derrière le nom.
"Serveur externe" fait référence à des serveurs situés à l'extérieur de l'entreprise (a priori), qui ne sont pas connus dans l'inventaire GLPI. On peut donc effectivement saisir ce que l'on veut.
Si l'on fait référence à des serveurs internes, il est possible de le faire via l'onglet "Associated items".
Bien cordialement,
