### ISSUE TITLE
Evo : Longueur du flux

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-dataflows#15]
Bonjour

On a bien une notion de format à la source (qui pourrait être un intitulé ?) : OK

On n'a pas de notion de longueur du fichier transmis/recu ?

Merci

**Comment by ericferon** [comment]
Si, il y a une notion de "volume de transfert", en MB.
Bien cordialement,

**Comment by EC2311** [comment]
Pour moi le volume n'est pas identique à la longueur. (sauf traduction?)

-> via FTP on peut échanger des fichiers de longueurs fixées (80, 132 Caracteres, par exemple)
il faut que emetteur et recepteur aient les memes caractéristiques. et c'est ce que je comprends dans 'longueur'.

**Comment by ericferon** [comment]
Effectivement.
Selon moi, cette information fait partie du format (source ou destination).
Mais émetteur et récepteur ne doivent pas nécessairement être identiques.
Des transformations peuvent être effectuées entre les 2.
Bien cordialement,
