### ISSUE TITLE
EVO ? Lier Dataflow avec Applicatif et autre idée

### ISSUE THREAD

**Issue by EC2311** [ericferon/glpi-dataflows#16]
Bonjour

Dataflow est lié actuellement avec structure applicatif, votre plugin, qui fonctionne à merveille.

Avec le passage de appliances dans le coeur de GLPI, cela pourrait etre interessant de lier dataflows avec aussi applicatif, en fonction si structure d'applicatif est installé ou non (si non installé : select name, id from glpi_appliances, si installé select name, id from glpi_plugin_archisw_swcomponents)?

D'autre part, en utilisant dataflows, et donc structure d'appli, pourquoi ne pas 'visualiser' qu'une application possede un flux (en sortie ou en entree) : onglet dataflow : on verrait le nom du flux et le type (sortie/entree), cliquable bien sur ;)

QU'en pensez vous ?

**Comment by ericferon** [comment]
Bonjour,
L'association avec "Applicatif" a été ajoutée en v2.2.17.
Vos autres demandes sont trop complexes à réaliser (si on veut les réaliser proprement, en tenant compte des modifications possibles : commencer avec appliance puis activer ultérieureurement le plugin, ou l'inverse ...).
La visualisation des flux en entrée ou en sortie d'une structure d'appli est possible à partir de dataflow : il suffit d'effectuer une recherche sur le champ "From App" ou "To App"
Bien cordialement,
