### ISSUE TITLE
Lien Dataflow accounts

### ISSUE THREAD

**Issue by redfish8** [ericferon/glpi-dataflows#17]
Bonjour,
Sous GLPI 10.0.3 et DataFlow 2.2.14 les "Accounts" sont liés par Source User (ou Destination user). Le problème est que depuis le "Account" on a bien un onglet Dataflow mais les flux liés ne sont pas listés et que si on tente une association le menu déroulant ne propose que des "Flow Group".

J'espère que ma description du problème est claire, sinon dites-moi.

Merci

Patrick

**Comment by redfish8** [comment]
Je m'aperçois que l'association à des Dataflow est également possible dans les Projets et Tâches de Projet mais avec le même problème (seul le groupe de flux est proposé) et si on essaie quand même on a une erreur de droit (même en Super-Admin)

**Comment by ericferon** [comment]
En effet, il y avait un bug, corrigé en v2.2.15, dans l'affichage du groupe et des flux.
Par contre, il n'est pas prévu que le "Source user" ou "Destination user" utilisé soit reflété par une association, à moins que vous ne le gériez manuellement (ce serait difficile à maintenir).
Bien cordialement,
