### ISSUE TITLE
Liaison avec certificat - sécurité

### ISSUE THREAD

**Issue by redfish8** [ericferon/glpi-dataflows#18]
Bonjour,
Ne ferait-il pas sens de pouvoir lier un flux avec un certificat ?
D'une manière générale le plugin renseigne énormément d'infos sur le transport et les données mais pour l'aspect sécurité (cryptage, filtrage) je suis contraint d'utiliser des champs "libres", par ex preprocessing,  pour documenter cet aspect (en plus de authentication type).
Merci

**Comment by ericferon** [comment]
Bonjour,
L'association avec des certificats a été ajoutée en v2.2.17.
Bienb cordialement,
