### ISSUE TITLE
EVO ? Lier Dataflow dans l'analyse d'impact.

### ISSUE THREAD

**Issue by emgenet** [ericferon/glpi-dataflows#19]
Bonjour, j'ai posé la question sur le forum GLPI afin de trouver les éléments de ce plugin dans l'analyse d'impact, mais le retour est de vous poser la question.

Voici le sujet d'origine : [(https://forum.glpi-project.org/viewtopic.php?id=285272)]

Il est proposé de : modifier le code afin que les types d'éléments Dataflows soient ajoutés au tableau "$CFG_GLPI["impact_asset_types"]".

Merci d'avance.

**Comment by ericferon** [comment]
Impact analysis a été ajouté en v2.2.16.
Idem pour le plugin archisw (Apps structure), en v2.2.14.
Bien cordialement,
