### ISSUE TITLE
Error on dropdowns - Info

### ISSUE THREAD

**Issue by xventil** [ericferon/glpi-dataflows#21]
Hello, when i go to dataflows and select for example the from application ( and press the info button) i get the follow info/error

Unknown column 'glpi_plugin_dataflows_fromswcomponents.completename' in 'field list'

the same happens it i select  to aaplication

Unknown column 'glpi_plugin_dataflows_toswcomponents.completename' in 'field list'

any idea how we can correct this errors? seems some problem with the structure of the database

**Comment by ericferon** [comment]
Hi,
You should select the menu Setup>Dropdowns>Dataflows>Link classes and modify the record "PluginDataflowsFromSwcomponent. Choose "Yes" in the field "Is hierarchichal dropdown" : 
![image](https://github.com/ericferon/glpi-dataflows/assets/8736398/9eb28926-1621-4ecb-b7e2-705180d1fff6).
In your DB schema, you should find a view "glpi_plugin_dataflows_fromswcomponents" containg a field "completename", among others.
Idem for "PluginDataflowsToSwcomponent".
K.r,

**Comment by xventil** [comment]
Thank you for the quick reply.

i don´t have a link class there.. 
![imagem](https://github.com/ericferon/glpi-dataflows/assets/1051399/50530c98-c4bc-49cf-9972-b4b2df512671)

**Comment by ericferon** [comment]
Hi,
Strange.
Which plugin version is installed ? Not the last one (v3.0.9) ?
Have you a menu Setup>Dataflows configuration ?
K.r,

**Comment by xventil** [comment]
Hi,

yes, version 3.0.9,
![imagem](https://github.com/ericferon/glpi-dataflows/assets/1051399/fa3582ad-2aed-4863-bb12-09e29059c12d)

No, don´t have that menu...
![imagem](https://github.com/ericferon/glpi-dataflows/assets/1051399/793d1b2f-dc22-4521-bd5e-110200578dd7)

I tryed to remove and install again the plugin, but i´m getting error sql errors removing the DB. i have a UAT envierment that i can destroy and recreate without issues, so if you need me to test something, i´m glad to do it.

TY,
Best Regards,
and merry xmas to you and your family

**Comment by ericferon** [comment]
Hi,
Have you granted access to the Dataflows configuration in your profile (usually super-admin) ?
If yes, what's happening when you click on the 3d icon (wrench), on the plugin's tile ?
K.r,

**Comment by xventil** [comment]
Problem Solved! thank you very much.

Happy New Year
