### ISSUE TITLE
Error while creating a dataflow

### ISSUE THREAD

**Issue by Grougrou4** [ericferon/glpi-dataflows#22]
When i try to set a destination user on a dataflow, i got this error

![Capture d’écran 2024-03-05 133159](https://github.com/ericferon/glpi-dataflows/assets/116307181/f8791afc-76c9-43dd-8457-92ab9e93bfe9)

any idea why ?

thank you

**Comment by ericferon** [comment]
Hi,
For the usage of  "Source user" or "Destination user", the installation of the "Accounts" plugin is a pre-requisite.
Then you can configure the field (f.i plugin_dataflows_tocredentials_id) and the linked class as follows : 
![image](https://github.com/ericferon/glpi-dataflows/assets/8736398/96c0cf3d-7d48-4fda-aa0a-40caa72ed609)

![image](https://github.com/ericferon/glpi-dataflows/assets/8736398/10969104-5c2a-4a96-95a6-8e42fbb039a9)
K.r,

**Comment by Grougrou4** [comment]
Ok thanks for your response. is thaht the account inventory plugin from INFOTEL ?

**Comment by ericferon** [comment]
Yes.
K.r,
