### ISSUE TITLE
Unable to add 'other expert'

### ISSUE THREAD

**Issue by dramaker** [ericferon/glpi-dataflows#23]
In a new Dataflows entry, when selecting the plus sign of "Other Expert", an internal server error is shown.
In the php error log, below entry is saved.

------------------------------
[2024-04-23 16:59:42] glpiphplog.WARNING:   *** PHP User Warning (512): Table glpi_plugin_dataflows_otherusers does not exists in C:\inetpub\wwwroot\glpi\src\DBmysql.php at line 1240
  Backtrace :
  src\DBmysql.php:1240                               trigger_error()
  src\CommonDropdown.php:520                         DBmysql->fieldExists()
  src\CommonDBTM.php:3813                            CommonDropdown->rawSearchOptions()
  src\Search.php:8224                                CommonDBTM->searchOptions()
  src\Search.php:8018                                Search::getOptions()
  src\Search.php:2799                                Search::getCleanedOptions()
  src\Search.php:2605                                Search::displayCriteria()
  src\Search.php:171                                 Search::showGenericSearch()
  front\dropdown.common.php:52                       Search::show()
  plugins\dataflows\front\otheruser.php:28           include()
------------------------------

Apparently table glpi_plugin_dataflows_otherusers is missing but creating it was not allowed because a view with the same name already exists.

Any advice would be appreciated.

Kind regards.

**Comment by ericferon** [comment]
Hi,
Can you check how the field is defined in the "Setup>Dataflow configuration" menu and how the linked class is defined in the "Setup>Dropdowns>Dataflows>Linked classes" menu ? This should be "As view on table" glpi_users.
K.r,

**Comment by dramaker** [comment]
Thanks for replying.

Dataflow Configuration =
![image](https://github.com/ericferon/glpi-dataflows/assets/166832196/b8255848-fca0-435b-a753-6fc337ee2e09)

Linked class =
![image](https://github.com/ericferon/glpi-dataflows/assets/166832196/3a3233a1-c3a4-4506-8857-13f62617b922)

"As view on table" = glpi_users

Kind regards

**Comment by ericferon** [comment]
Hi,
The definitions are right.
In fact, you may not add new "Other expert" (even if there is a + sign), as other expert is chosen among the GLPI users.
If you want to add an other expert, you have to create a new GLPI user, or you have to change the class definition (do not refer to glpi_users).
K.r,

**Comment by dramaker** [comment]
Hi,
Maybe I wasn't clear.
'Other expert' is not chosen among the GLPI users because the dropdown is empty and clicking the "i" gives an internal server error. Filling up the dropdown is not possible as the + sign also gives an internal server error.
We want to use this field to literally add other experts, people who are not listed as GLPI users.
How do we get rid of the internal server errors? It would be great if we can link an empty table to 'Other expert' that we can fill up using the + sign. However all my attempts have failed so far.
Kind regards.

**Comment by ericferon** [comment]
Hi,
To link an empty table, you should delete the linked class PluginDataflowsOtherUser : this will delete the corresponding view in the DB. Then create a new class PluginDataflowsOtherUser, with the field "as view on table" empty. This will create a new table. You have then to fill again the field "Linked class" in the Dataflows Config.
K.r,
