### ISSUE TITLE
Dataflow name limited to 46 characters 

### ISSUE THREAD

**Issue by redfish8** [ericferon/glpi-dataflows#24]
When editing or creating a dataflow the field "Name" seems limited to 46 characters which looks a bit small (at least for my usage). Is this by design or something in my configuration ?

Thank you

Patrick

**Comment by ericferon** [comment]
Hi,
The "name" field has a length of 45 characters, by design : this length is the one of other "name" fields throughout glpi.
I could extend it, but what is the right length ? There will always be someone to say : "it's too short" :-)
What would your ideal length be ? 80 ? 100 ?
K.r,

**Comment by redfish8** [comment]
Hello,
Thank you for the reply, I use quite a lot of different GLPI objects and was hit by the naming size limit only for the Data flows, may be our naming convention is to verbose. I agree with you that there will be always someone asking for more but if you ask me 70 would be enough because currently I can fit in the limits by shortening one or two words.
I didn't check what is the usual size limit of other GLPI objects but i.e. i have a Certificate with 98 characters length.

Thank you

**Comment by ericferon** [comment]
Increased to 100 characters in v3.0.13.
K.r,
