### ISSUE TITLE
Dataflow not displaying Changes or Problems

### ISSUE THREAD

**Issue by redfish8** [ericferon/glpi-dataflows#25]
Hello,
We can associate a change or a problem with a Dataflow, but in the Dataflow itself the Changes and the Problems tabs are not visible.
Using SuperAdmin role and Dataflow 3.0.12 on GLPI 10.0.15.

Let me know if I can check something.

Patrick

**Comment by ericferon** [comment]
Fixed in v3.0.13
K.r
