### ISSUE TITLE
Error when showing dataflows in computer

### ISSUE THREAD

**Issue by redfish0** [ericferon/glpi-dataflows#4]
Hello,
When I have a dataflow linked to a computer I get :

`Fatal error: Uncaught Error: Class 'PluginDataflowsServerType' not found in /var/www/glpi/plugins/dataflows/inc/dataflow_item.class.php:492 Stack trace: #0 /var/www/glpi/plugins/dataflows/inc/dataflow_item.class.php(122): PluginDataflowsDataflow_Item::showForItem(Object(Computer)) #1 /var/www/glpi/inc/commonglpi.class.php(482): PluginDataflowsDataflow_Item::displayTabContentForItem(Object(Computer), '1', '') #2 /var/www/glpi/ajax/common.tabs.php(96): CommonGLPI::displayStandardTab(Object(Computer), 'PluginDataflows...', '', Array) #3 {main} thrown in /var/www/glpi/plugins/dataflows/inc/dataflow_item.class.php on line 492`

And when there is no dataflow associated with the computer I get :
`Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in /var/www/glpi/inc/dbmysql.class.php:312 Stack trace: #0 /var/www/glpi/plugins/dataflows/inc/dataflow.class.php(571): DBmysql->fetch_assoc(false) #1 /var/www/glpi/plugins/dataflows/inc/dataflow_item.class.php(462): PluginDataflowsDataflow::dropdownDataflow(Array) #2 /var/www/glpi/plugins/dataflows/inc/dataflow_item.class.php(122): PluginDataflowsDataflow_Item::showForItem(Object(Computer)) #3 /var/www/glpi/inc/commonglpi.class.php(482): PluginDataflowsDataflow_Item::displayTabContentForItem(Object(Computer), '1', '') #4 /var/www/glpi/ajax/common.tabs.php(96): CommonGLPI::displayStandardTab(Object(Computer), 'PluginDataflows...', '', Array) #5 {main} thrown in /var/www/glpi/inc/dbmysql.class.php on line 312`

**Comment by ericferon** [comment]
Solved in v2.0.6, just released
Thank you for reporting this bug.
Best regards,
