### ISSUE TITLE
Display dataflows in archisw

### ISSUE THREAD

**Issue by redfish0** [ericferon/glpi-dataflows#5]
Hello,
I think it could be interesting to display all dataflows related with an app (either source or destination). Is it feasible ?

Thanks for all the improvments in the two plugins.

Patrick

**Comment by ericferon** [comment]
It's feasible : you can search dataflows that match 2 criteria :


- "from app" "is" applicationX 

- OR "to app" "is" applicationX


Best regards, 

On Tue, 11 Sep 2018 08:24:04 +0000 (UTC), redfish0
wrote: 

> Hello,
> I think it could be interesting to display all
dataflows related with an app (either source or destination). Is it
feasible ? 
> 
> Thanks for all the improvments in the two plugins. 
>

> Patrick 
> 
> --
> You are receiving this because you are subscribed
to this thread.
> Reply to this email directly, view it on GitHub [1],
or mute the thread [2].
 

Links:
------
[1]
https://github.com/ericferon/glpi-dataflows/issues/5
[2]
