### ISSUE TITLE
erreurs multiples dans sql-errors.og

### ISSUE THREAD

**Issue by yalgva** [ericferon/glpi-dataflows#9]
Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DROP VIEW IF EXISTS `glpi_plugin_dataflows_tocredentials`;
CREATE OR REPLACE VIE' at line 6
  Backtrace :
  inc\dbmysql.class.php:539                          
  plugins\dataflows\hook.php:35                      DBmysql->runFile()
  inc\plugin.class.php:707                           plugin_dataflows_install()
  front\plugin.form.php:47                           Plugin->install()
  {"user":"2430@GLPI02","mem_usage":"0.000\", 2.84Mio)"} 
[2018-12-05 09:51:08] glpisqllog.ERROR: DBmysql::query() in C:\inetpub\wwwroot\inc\dbmysql.class.php line 177
  *** MySQL query error:
  SQL: CREATE OR REPLACE VIEW glpi_plugin_dataflows_fromcredentials as
SELECT `id`,`name`, `login` as comment FROM glpi_plugin_accounts_accounts;
-- -----------------------------------------------------
-- Table `glpi_plugin_dataflows_tocredentials`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `glpi_plugin_dataflows_tocredentials`;
CREATE OR REPLACE VIEW glpi_plugin_dataflows_tocredentials as
SELECT `id`,`name`, `login` as comment FROM glpi_plugin_accounts_accounts;

-- -----------------------------------------------------
-- View `glpi_plugin_dataflows_fromswcomponents`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `glpi_plugin_dataflows_fromswcomponents`;
CREATE OR REPLACE VIEW `glpi_plugin_dataflows_fromswcomponents` (`id`, `entities_id`, `name`, `comment`) AS
SELECT `id`, `entities_id`, `completename`, `comment` from `glpi_plugin_archisw_swcomponents` where level = '1';

-- -----------------------------------------------------
-- View `glpi_plugin_dataflows_toswcomponents`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `glpi_plugin_dataflows_toswcomponents`;
CREATE OR REPLACE VIEW `glpi_plugin_dataflows_toswcomponents` (`id`, `entities_id`, `name`, `comment`) AS
SELECT `id`, `entities_id`, `completename`, `comment` from `glpi_plugin_archisw_swcomponents` where level = '1';

-- -----------------------------------------------------
-- View `glpi_plugin_dataflows_fromcomputers`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `glpi_plugin_dataflows_fromcomputers`;
CREATE OR REPLACE VIEW `glpi_plugin_dataflows_fromcomputers` (`id`, `entities_id`, `name`, `comment`) AS
SELECT `id`, `entities_id`, `name`, `comment` from `glpi_computers`;

-- -----------------------------------------------------
-- View `glpi_plugin_dataflows_tocomputers`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `glpi_plugin_dataflows_tocomputers`;
CREATE OR REPLACE VIEW `glpi_plugin_dataflows_tocomputers` (`id`, `entities_id`, `name`, `comment`) AS
SELECT `id`, `entities_id`, `name`, `comment` from `glpi_computers`;

-- -----------------------------------------------------
-- View `glpi_plugin_dataflows_othergroups`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `glpi_plugin_dataflows_othergroups`;
CREATE OR REPLACE VIEW `glpi_plugin_dataflows_othergroups` AS
SELECT * from `glpi_groups`;

-- -----------------------------------------------------
-- View `glpi_plugin_dataflows_supportgroups`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `glpi_plugin_dataflows_supportgroups`;
CREATE OR REPLACE VIEW `glpi_plugin_dataflows_supportgroups` AS
SELECT * from `glpi_groups`;

-- -----------------------------------------------------
-- View `glpi_plugin_dataflows_otherusers`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `glpi_plugin_dataflows_otherusers`;
CREATE OR REPLACE VIEW `glpi_plugin_dataflows_otherusers` AS
SELECT * from `glpi_users`;

-- -----------------------------------------------------
-- Table `plugin_dataflows_triggertypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glpi_plugin_dataflows_triggertypes`;
CREATE  TABLE IF NOT EXISTS `glpi_plugin_dataflows_triggertypes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL ,
  `comment` VARCHAR(45) NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `plugin_dataflows_triggertype_name` (`name` ASC) )
ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
insert glpi_plugin_dataflows_triggertypes (name,comment) values 
('FILE','Flow triggered by file presence'),
('EVENTJMS','Flow triggered by JMS event message');

-- -----------------------------------------------------
-- Table `plugin_dataflows_transferfreqs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glpi_plugin_dataflows_transferfreqs`;
CREATE  TABLE IF NOT EXISTS `glpi_plugin_dataflows_transferfreqs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL ,
  `comment` VARCHAR(45) NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `plugin_dataflows_transferfreq_name` (`name` ASC) )
ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `plugin_dataflows_transfertimetables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glpi_plugin_dataflows_transfertimetables`;
CREATE  TABLE IF NOT EXISTS `glpi_plugin_dataflows_transfertimetables` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL ,
  `comment` VARCHAR(45) NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `plugin_dataflows_transfertimetable_name` (`name` ASC) )
ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `plugin_dataflows_holidayactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glpi_plugin_dataflows_holidayactions`;
CREATE  TABLE IF NOT EXISTS `glpi_plugin_dataflows_holidayactions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL ,
  `comment` VARCHAR(45) NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `plugin_dataflows_holidayaction_name` (`name` ASC) )
ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `plugin_dataflows_srcuris`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glpi_plugin_dataflows_srcuris`;
CREATE  TABLE IF NOT EXISTS `glpi_plugin_dataflows_srcuris` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL ,
  `comment` VARCHAR(45) NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `plugin_dataflows_srcuri_name` (`name` ASC) )
ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `plugin_dataflows_srcpreprocs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glpi_plugin_dataflows_srcpreprocs`;
CREATE  TABLE IF NOT EXISTS `glpi_plugin_dataflows_srcpreprocs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL ,
  `comment` VARCHAR(45) NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `plugin_dataflows_srcpreproc_name` (`name` ASC) )
ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `plugin_dataflows_desturis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glpi_plugin_dataflows_desturis`;
CREATE  TABLE IF NOT EXISTS `glpi_plugin_dataflows_desturis` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL ,
  `comment` VARCHAR(45) NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `plugin_dataflows_desturi_name` (`name` ASC) )
ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `plugin_dataflows_destpostprocs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glpi_plugin_dataflows_destpostprocs`;
CREATE  TABLE IF NOT EXISTS `glpi_plugin_dataflows_destpostprocs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL ,
  `comment` VARCHAR(45) NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `plugin_dataflows_destpostproc_name` (`name` ASC) )
ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `plugin_dataflows_errorhandlings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `glpi_plugin_dataflows_errorhandlings`;
CREATE  TABLE IF NOT EXISTS `glpi_plugin_dataflows_errorhandlings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL ,
  `comment` VARCHAR(45) NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `plugin_dataflows_errorhandling_name` (`name` ASC) )
ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `glpi_displaypreferences` VALUES (NULL,'PluginDataflowsDataflow','2','2','0');
INSERT INTO `glpi_displaypreferences` VALUES (NULL,'PluginDataflowsDataflow','6','3','0');
INSERT INTO `glpi_displaypreferences` VALUES (NULL,'PluginDataflowsDataflow','7','4','0');
	

  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DROP VIEW IF EXISTS `glpi_plugin_dataflows_tocredentials`;
CREATE OR REPLACE VIE' at line 6
  Backtrace :
  inc\dbmysql.class.php:539                          
  plugins\dataflows\hook.php:35                      DBmysql->runFile()
  inc\plugin.class.php:707                           plugin_dataflows_install()
  front\plugin.form.php:47                           Plugin->install()
  {"user":"2430@GLPI02","mem_usage":"0.000\", 2.84Mio)"} 
[2018-12-05 09:51:25] glpisqllog.ERROR: DBmysql::query() in C:\inetpub\wwwroot\inc\dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_bookmarks` WHERE `itemtype` LIKE 'PluginArchifun%' ;
  Error: Table 'glpi93.glpi_bookmarks' doesn't exist
  Backtrace :
  plugins\archifun\hook.php:123                      
  inc\plugin.class.php:659                           plugin_archifun_uninstall()
  front\plugin.form.php:47                           Plugin->uninstall()
  {"user":"2430@GLPI02"}

**Comment by yalgva** [comment]
Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DROP VIEW IF EXISTS `glpi_plugin_dataflows_tocredentials`;
CREATE OR REPLACE VIE' at line 6
  Backtrace :
  inc\dbmysql.class.php:539                          
  plugins\dataflows\hook.php:35                      DBmysql->runFile()
  inc\plugin.class.php:707                           plugin_dataflows_install()
  front\plugin.form.php:47                           Plugin->install()
  {"user":"2430@GLPI02","mem_usage":"0.000\", 2.84Mio)"} 
[2018-12-05 09:51:25] glpisqllog.ERROR: DBmysql::query() in C:\inetpub\wwwroot\inc\dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_bookmarks` WHERE `itemtype` LIKE 'PluginArchifun%' ;
  Error: Table 'glpi93.glpi_bookmarks' doesn't exist
  Backtrace :
  plugins\archifun\hook.php:123                      
  inc\plugin.class.php:659                           plugin_archifun_uninstall()
  front\plugin.form.php:47                           Plugin->uninstall()
  {"user":"2430@GLPI02"}

**Comment by yalgva** [comment]
2018-12-05 09:51:45 [2430@GLPI02]
  Backtrace :
  inc\toolbox.class.php:562                          Toolbox::backtrace()
  inc\dbutils.class.php:323                          Toolbox::deprecated()
  inc\db.function.php:178                            DbUtils->countElementsInTable()
  plugins\archisw\inc\swcomponent_item.class.php:143 countElementsInTable()
  plugins\archisw\inc\swcomponent_item.class.php:95  PluginArchiswSwcomponent_Item::countForItem()
  inc\commonglpi.class.php:210                       PluginArchiswSwcomponent_Item->getTabNameForItem()
  inc\commonglpi.class.php:173                       CommonGLPI->addStandardTab()
  ajax\updatecurrenttab.php:46                       CommonGLPI->defineAllTabs()
2018-12-05 09:51:45 [2430@GLPI02]
  Backtrace :
  inc\toolbox.class.php:562                          Toolbox::backtrace()
  inc\dbutils.class.php:323                          Toolbox::deprecated()
  inc\db.function.php:178                            DbUtils->countElementsInTable()
  plugins\dataflows\inc\dataflow_item.class.php:143  countElementsInTable()
  plugins\dataflows\inc\dataflow_item.class.php:95   PluginDataflowsDataflow_Item::countForItem()
  inc\commonglpi.class.php:210                       PluginDataflowsDataflow_Item->getTabNameForItem()
  inc\commonglpi.class.php:173                       CommonGLPI->addStandardTab()
  ajax\updatecurrenttab.php:46                       CommonGLPI->defineAllTabs()
2018-12-05 09:51:45 [2430@GLPI02]
  Backtrace :
  inc\toolbox.class.php:562                          Toolbox::backtrace()
  inc\dbutils.class.php:323                          Toolbox::deprecated()
  inc\db.function.php:178                            DbUtils->countElementsInTable()
  plugins\archifun\inc\funcarea_item.class.php:143   countElementsInTable()
  plugins\archifun\inc\funcarea_item.class.php:95    PluginArchifunFuncarea_Item::countForItem()
  inc\commonglpi.class.php:210                       PluginArchifunFuncarea_Item->getTabNameForItem()
  inc\commonglpi.class.php:173                       CommonGLPI->addStandardTab()
  ajax\updatecurrenttab.php:46                       CommonGLPI->defineAllTabs()

**Comment by ericferon** [comment]
The dataflows plugin uses 2 views on tables created by the accounts plugin.
So, at installation, there is an error because the 2 views cannot be created.
But the code checks whether the accounts plugin is enabled or not, and takes the needed actions if it is not.
I will try to suppress these error message in a future version.
Best regards,
